services:
  dao-database:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - kotlin-db-data:/var/lib/postgresql/data

volumes:
  kotlin-db-data: